import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from data import max_speed

class SpeedOperations:
    @staticmethod
    def increase_speed(plane) -> str:
        """
        Increases the speed of the plane until it reaches a random speed
        generated by max_speed(). The speed is increased by 9 km/h each time.
        If the speed reaches 200 km/h and the plane is not flying, 
        it takes off.
        """
        target_speed = max_speed()
        while plane.speed < target_speed:
            if plane.speed >= 200 and not plane.is_flying:
                plane.is_flying = True
                print(f"The plane took off. Speed: {plane.speed} km/h")
            plane.speed += 9
            print(f"Speed: {plane.speed} km/h")
        
        print(f"Target speed of {target_speed} km/h reached!")
        # After reaching the max speed, start decreasing the speed
        return SpeedOperations.decrease_speed(plane)
    
    @staticmethod
    def decrease_speed(plane) -> str:
        """
        Decreases the speed of the plane until it reaches 0 km/h.
        If the speed goes below 200 km/h and the plane is flying, it lands.
        """
        while plane.speed > 0:
            plane.speed -= 9
            if plane.speed < 200 and plane.is_flying:
                plane.is_flying = False
                print(f"The plane landed. Speed: {plane.speed} km/h")
            print(f"Speed: {plane.speed} km/h")
        return f"Speed decreased to {plane.speed} km/h"
